Models/Category.cs
namespace DotnetMvc.Models;

public class Category
{
    public int Id { get; set; }
    public string Name { get; set; }
    public ICollection<Item> Items { get; set; }

}

Models/ErrorViewModel.cs
namespace DotnetMvc.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }
    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Item.cs
namespace DotnetMvc.Models;

public class Item
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public decimal Price { get; set; }
    public int CategoryID { get; set; }
    public Category Category { get; set; }
    public string ImageUrl { get; set; }
}

Controllers/CategoryController.cs
using DotnetMvc.Repository;
using DotnetMvc.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DotnetMvc.Controllers;


public class CategoryController : Controller
{
    private readonly CategoryRepository _categoryRepository;
    public CategoryController(CategoryRepository categoryRepository)
    {
        _categoryRepository = categoryRepository;
    }

    public async Task<IActionResult> Index(bool isCreated = false)
    {
        var categories = await _categoryRepository.GetAllCategories();

        if (isCreated == true)
        {
            ViewBag.IsCreated = isCreated;
            ViewBag.Message = "Item Created Successfully";
        }


        return View(categories);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var category = await _categoryRepository.GetCategoryById(id);
        return View(category);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, CategoryVM categoryVM)
    {
        if (id != categoryVM.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            await _categoryRepository.UpdateCategory(categoryVM);
            return RedirectToAction("Index", new { isUpdated = true });
        }
        return View(categoryVM);
    }

    public IActionResult create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> create(CategoryVM categoryVM)
    {
        if (ModelState.IsValid)
        {
            await _categoryRepository.CreateCategory(categoryVM);
            return RedirectToAction("Index", new { isCreated = true });
        }
        return View(categoryVM);
    }

    public async Task<IActionResult> Delete(int id)
    {
        var category = await _categoryRepository.GetCategoryById(id);
        return View(category);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(int id, CategoryVM categoryVM)
    {
        await _categoryRepository.DeleteCategory(id);
        return RedirectToAction("Index", new { isDeleted = true });
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DotnetMvc.Models;

namespace DotnetMvc.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ItemController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DotnetMvc.Models;
using DotnetMvc.Repository;
using Microsoft.AspNetCore.Mvc.Rendering;
using DotnetMvc.ViewModels;

namespace DotnetMvc.Controllers;

public class ItemController : Controller
{
    private readonly ItemRepository _itemRepository;
    private readonly CategoryRepository _categoryRepository;
    private readonly IWebHostEnvironment _webHostEnvironment;
    public ItemController(ItemRepository itemRepository, CategoryRepository categoryRepository, IWebHostEnvironment webHostEnvironment)
    {
        _itemRepository = itemRepository;
        _categoryRepository = categoryRepository;
        _webHostEnvironment = webHostEnvironment;
    }

    public async Task<IActionResult> Index(bool isDeleted = false, bool isCreated = false, bool isUpdated = false)
    {
        var items = await _itemRepository.GetAllItems();
        if (isDeleted == true)
        {
            ViewBag.IsDeleted = isDeleted;
            ViewBag.Message = "Item Deleted Successfully";
        }

        if (isCreated == true)
        {
            ViewBag.IsCreated = isCreated;
            ViewBag.Message = "Item Created Successfully";
        }

        if (isUpdated == true)
        {
            ViewBag.IsUpdated = isUpdated;
            ViewBag.Message = "Item Updated Successfully";
        }
        return View(items);
    }

    public async Task<IActionResult> Details(int id)
    {
        var item = await _itemRepository.GetItemById(id);
        return View(item);
    }

    public async Task<IActionResult> Delete(int id)
    {
        var item = await _itemRepository.GetItemById(id);
        return View(item);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(int id, Item item)
    {
        await _itemRepository.DeleteItem(id);
        return RedirectToAction("Index", new { isDeleted = true });
    }

    public async Task<IActionResult> Create()
    {
        var categories = await _categoryRepository.GetAllCategories();
        ViewBag.Categories = categories.Select(c => new SelectListItem
        {
            Text = c.Name,
            Value = c.Id.ToString()
        });

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(ItemVM item)
    {
        if (ModelState.IsValid)
        {
            if (item.Image != null)
            {
                string folder = "items/image";
                string filePath = await UploadImage(folder, item.Image);
                item.ImageUrl = filePath;
            }
            else
            {
                item.ImageUrl = "/items/image\\default.jpg";
            }

            await _itemRepository.CreateItem(item);
            return RedirectToAction("Index", new { isCreated = true });
        }

        var categories = await _categoryRepository.GetAllCategories();
        ViewBag.Categories = categories.Select(c => new SelectListItem
        {
            Text = c.Name,
            Value = c.Id.ToString()
        });

        return View(item);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var item = await _itemRepository.GetItemById(id);
        var categories = await _categoryRepository.GetAllCategories();
        ViewBag.Categories = categories.Select(c => new SelectListItem
        {
            Text = c.Name,
            Value = c.Id.ToString()
        });

        return View(item);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, ItemVM item)
    {
        if (id != item.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            if (item.Image != null)
            {
                string folder = "items/image";
                string filePath = await UploadImage(folder, item.Image);
                item.ImageUrl = filePath;
            }



            await _itemRepository.UpdateItem(item);
            return RedirectToAction("Index", new { isUpdated = true });
        }
        return View(item);
    }

    private async Task<string> UploadImage(string folderPath, IFormFile file)
    {
        string fileName = Guid.NewGuid().ToString() + "_" + file.FileName;
        string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath, fileName);
        string filePath = Path.Combine(folderPath, fileName);

        using (var stream = new FileStream(serverFolder, FileMode.Create))
        {
            await file.CopyToAsync(stream);
        }

        return "/" + filePath;
    }

}

Views/Category/Create.cshtml
@model CategoryVM

@{
    ViewData["Title"] = "Create Category";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Category List</a>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Category/Delete.cshtml
@model ItemVM

@{
    ViewData["Title"] = "Delete Category";
}

<h1>@ViewData["Title"]</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            ID
        </dt>
        <dd class="col-sm-10">
            @Model.Id
        </dd>
        <dt class="col-sm-2">
            NAME
        </dt>
        <dd class="col-sm-10">
            @Model.Name
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to Category List</a>
    </form>
</div>

Views/Category/Edit.cshtml
@model CategoryVM;

@{
    ViewData["Title"] = "Edit Category";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Category List</a>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Category/index.cshtml
@model List<CategoryVM>

@{
    ViewData["Title"] = "Create Category";
}

@* ViewBag.isDeleted == true || *@
@if (ViewBag.IsCreated == true)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>@ViewBag.message</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<p>
    <a asp-action="Create">@ViewData["Title"]</a>
</p>

<table class="table ">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var category in Model)
        {
            <tr>
                <td>
                    @category.Id
                </td>
                <td>
                    @category.Name
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@category.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@category.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Item/Create.cshtml
@model ItemVM

@{
    ViewData["Title"] = "Create Item";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CategoryID" class="form-label"></label>
                <select asp-for="CategoryID" class="form-control" asp-items="@ViewBag.Categories">
                    <option value="" selected>Select Language</option>
                </select>
                <span asp-validation-for="CategoryID" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Image" class="form-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Item List</a>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Item/Delete.cshtml
@model ItemVM

@{
    ViewData["Title"] = "Delete Item";
}

<h1>@ViewData["Title"]</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            ID
        </dt>
        <dd class="col-sm-10">
            @Model.Id
        </dd>
        <dt class="col-sm-2">
            NAME
        </dt>
        <dd class="col-sm-10">
            @Model.Name
        </dd>
        <dt class="col-sm-2">
            Description
        </dt>
        <dd class="col-sm-10">
            @Model.Description
        </dd>
        <dt class="col-sm-2">
            Price
        </dt>
        <dd class="col-sm-10">
            @Model.Price
        </dd>
        <dt class="col-sm-2">
            Category
        </dt>
        <dd class="col-sm-10">
            @Model.CategoryName
        </dd>
        <dt class="col-sm-2">
            Image
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.ImageUrl" class="coverphoto" />
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to Item List</a>
    </form>
</div>

Views/Item/Details.cshtml
@model ItemVM

@{
    ViewData["Title"] = "Item Details";
}

<h1>@ViewData["Title"]</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            ID
        </dt>
        <dd class="col-sm-10">
            @Model.Id
        </dd>
        <dt class="col-sm-2">
            NAME
        </dt>
        <dd class="col-sm-10">
            @Model.Name
        </dd>
        <dt class="col-sm-2">
            Description
        </dt>
        <dd class="col-sm-10">
            @Model.Description
        </dd>
        <dt class="col-sm-2">
            Price
        </dt>
        <dd class="col-sm-10">
            @Model.Price
        </dd>
        <dt class="col-sm-2">
            Category
        </dt>
        <dd class="col-sm-10">
            @Model.CategoryName
        </dd>
        <dt class="col-sm-2">
            Image
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.ImageUrl" class="coverphoto" />
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to Item List</a>
</div>

Views/Item/Edit.cshtml
@model ItemVM;

@{
    ViewData["Title"] = "Edit Item";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryID" class="form-label"></label>
                <select asp-for="CategoryID" class="form-control" asp-items="@ViewBag.Categories">
                    <option value="" selected>Select Language</option>
                </select>
                <span asp-validation-for="CategoryID" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Image" class="form-label"></label>
                <input asp-for="Image" class="form-control">
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div>
                <input type="hidden" asp-for="ImageUrl" value="@Model.ImageUrl">
                <p class="text-info">current image</p>
                <img src="@Model.ImageUrl" class="coverphoto" />
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Item List</a>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Item/index.cshtml
@model List<ItemVM>

@{
    ViewData["Title"] = "List Item";
}

<h1>@ViewData["Title"] </h1>


@if (ViewBag.isDeleted == true || ViewBag.IsCreated == true)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>@ViewBag.message</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}


<p>
    <a asp-action="Create">Create new Item</a>
</p>

<table class="table ">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Price
            </th>
            <th>
                Category
            </th>
            <th>
                Images
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @* @foreach (var book in Model)
            {
            <tr>
            <td>
            @book.Id
            </td>
            <td>
            @book.Name
            </td>
            <td>
            @book.Description
            </td>
            <td>
            @book.Price
            </td>
            <td>
            @book.CategoryName
            </td>
            <td>

            <a>Edit</a> |
            <a asp-action="Details" asp-route-id="@book.Id">Details</a> |
            <a asp-action="Delete" asp-route-id="@book.Id">Delete</a>
            </td>
            </tr>
            } *@


        @* loop to models using for loop *@

        @for (int i = 0; i < Model.Count(); i++)
        {
            <tr>
                <td>
                    @(i+1)
                </td>
                <td>
                    @Model[i].Name
                </td>
                <td>
                    @Model[i].Description
                </td>
                <td>
                    @Model[i].Price
                </td>
                <td>
                    @Model[i].CategoryName
                </td>
                <td>
                    <img src="@Model[i].ImageUrl" class="coverphoto" />
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@Model[i].Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@Model[i].Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@Model[i].Id">Delete</a>
                </td>
            </tr>
        }


    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotnetMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DotnetMvc.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DotnetMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="index">Item</a>
                            </li> *@

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Item
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Item" asp-action="index">
                                        List
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Item" asp-action="create">
                                        Create
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Category
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="index">
                                        List
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="create">
                                        Create
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DotnetMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>